USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE IF NOT EXISTS albums (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL,
  release_date INT UNSIGNED NOT NULL,
  sales FLOAT NOT NULL,
  genre VARCHAR(128),
  PRIMARY KEY(id)
);
